---
apiVersion: v1
kind: Namespace
metadata:
  name: configbackup
  labels:
    name: configbackup
---
# Read more about storage classes at https://learn.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv
apiVersion: v1
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: shgw-1-pvc
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Standard_LRS
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shgwcb-env
  namespace: configbackup
  labels:
    app: shgwcb
data:
  config.service.endpoint: "apim-peterlil.configuration.azure-api.net"
  neighborhood.host: "shgwcb-instance-discovery"
  runtime.deployment.artifact.source: "Azure Portal"
  runtime.deployment.mechanism: "YAML"
  runtime.deployment.orchestrator.type: "Kubernetes"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shgwcb
  namespace: configbackup
  labels:
    app: shgwcb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shgwcb
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: shgwcb
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: shgwcb
        image: mcr.microsoft.com/azure-api-management/gateway:v2
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8081
          # Container port used for rate limiting to discover instances
        - name: rate-limit-dc
          protocol: UDP
          containerPort: 4290
          # Container port used for instances to send heartbeats to each other
        - name: dc-heartbeat
          protocol: UDP
          containerPort: 4291
        readinessProbe:
          httpGet:
            path: /status-0123456789abcdef
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: config.service.auth
          valueFrom:
            secretKeyRef:
              name: shgwcb-token
              key: value
        envFrom:
        - configMapRef:
            name: shgwcb-env
---
apiVersion: v1
kind: Service
metadata:
  name: shgwcb-live-traffic
  namespace: configbackup
  labels:
    app: shgwcb
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8081
  selector:
    app: shgwcb
---
apiVersion: v1
kind: Service
metadata:
  name: shgwcb-instance-discovery
  namespace: configbackup
  labels:
    app: shgwcb
  annotations:
    azure.apim.kubernetes.io/notes: "Headless service being used for instance discovery of self-hosted gateway"
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: rate-limit-discovery
    port: 4290
    targetPort: rate-limit-dc
    protocol: UDP
  - name: discovery-heartbeat
    port: 4291
    targetPort: dc-heartbeat
    protocol: UDP
  selector:
    app: shgwcb